# Generated by Django 5.0.4 on 2024-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('course', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')])),
            ],
        ),
    ]
