# Generated by Django 5.0.4 on 2024-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
