# Generated by Django 5.0.4 on 2024-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='media/passports'),
        ),
    ]
